<a href="https://colab.research.google.com/github/cxbxmxcx/Practical_AI_on_GCP/blob/master/Chapter_7_Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

Create the initial set of inputs

In [2]:
x = [
  [1., 0., 1., 0.], # Input 1
  [0., .5, 0., .5], # Input 2
  [.75, .75, .75, .75]  # Input 3
 ]
x = np.array(x)

Initialize Key, Query and Value

In [3]:
w_key = [
  [1, 1, 1],
  [1, 1, 1],
  [1, 1, 1],
  [1, 1, 1]
]
w_query = [
  [1, 0, 1],
  [1, 0, 0],
  [0, 0, 1],
  [0, 1, 1]
]
w_value = [
  [2, 2, 2],
  [3, 3, 3],
  [4, 4, 4],
  [5, 5, 5]
]

w_key = np.array(w_key)
w_query = np.array(w_query)
w_value = np.array(w_value)

In [4]:
keys = x @ w_key
querys = x @ w_query
values = x @ w_value

print(keys)
print(querys)
print(values)

[[2. 2. 2.]
 [1. 1. 1.]
 [3. 3. 3.]]
[[1.   0.   2.  ]
 [0.5  0.5  0.5 ]
 [1.5  0.75 2.25]]
[[ 6.   6.   6. ]
 [ 4.   4.   4. ]
 [10.5 10.5 10.5]]


Calculate Attention Scores

In [5]:
attn_scores = (querys @ keys.T)
print(attn_scores)

[[ 6.   3.   9. ]
 [ 3.   1.5  4.5]
 [ 9.   4.5 13.5]]


Calculate Softmax over Attention

In [6]:
attn_scores_softmax = tf.nn.softmax(attn_scores, axis=-1).numpy()
attn_scores_softmax = np.round(attn_scores_softmax, decimals=2)
print(attn_scores_softmax)

[[0.05 0.   0.95]
 [0.18 0.04 0.79]
 [0.01 0.   0.99]]


Scors * Values

In [7]:
weighted_values = values[:,None] * attn_scores_softmax.T[:,:,None]
print(weighted_values)

[[[ 0.3    0.3    0.3  ]
  [ 1.08   1.08   1.08 ]
  [ 0.06   0.06   0.06 ]]

 [[ 0.     0.     0.   ]
  [ 0.16   0.16   0.16 ]
  [ 0.     0.     0.   ]]

 [[ 9.975  9.975  9.975]
  [ 8.295  8.295  8.295]
  [10.395 10.395 10.395]]]


Sum the weighted values

In [8]:
outputs = np.sum(weighted_values, axis=0)
print(outputs)

[[10.275 10.275 10.275]
 [ 9.535  9.535  9.535]
 [10.455 10.455 10.455]]
